on:
  push:
    branches:
      - main  # Corrected spacing

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Connect and Pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd ${{ secrets.WORK_DIR }}
        git fetch --all
        git checkout ${{ secrets.MAIN_BRANCH }}
        git pull origin ${{ secrets.MAIN_BRANCH }}
        EOF

    - name: Cleanup
      run: rm -rf ~/.ssh
